# modules/rgb_editor/effects.py
"""Définitions des types d'effets RGB disponibles.

Module pur Python sans dépendance Qt.
"""
from __future__ import annotations

from typing import NamedTuple


class EffectDef(NamedTuple):
    id: str            # stocké dans RgbEffect.type (rétro-compat : "static" conservé)
    name: str          # affiché dans le combo
    description: str   # affiché sous le combo
    preview: str       # type d'animation de preview
    category: str = "ambient"  # "ambient" | "reactive"
    custom: bool = False       # True = génère du code firmware


# Mapping effect_id → nom de la constante QMK RGB_MATRIX_*
EFFECT_QMK_MODE: dict[str, str] = {
    "static": "RGB_MATRIX_SOLID_COLOR",
    "alphas_mods": "RGB_MATRIX_ALPHAS_MODS",
    "gradient_up_down": "RGB_MATRIX_GRADIENT_UP_DOWN",
    "gradient_left_right": "RGB_MATRIX_GRADIENT_LEFT_RIGHT",
    "breathing": "RGB_MATRIX_BREATHING",
    "band_sat": "RGB_MATRIX_BAND_SAT",
    "band_val": "RGB_MATRIX_BAND_VAL",
    "band_pinwheel_sat": "RGB_MATRIX_BAND_PINWHEEL_SAT",
    "band_pinwheel_val": "RGB_MATRIX_BAND_PINWHEEL_VAL",
    "band_spiral_sat": "RGB_MATRIX_BAND_SPIRAL_SAT",
    "band_spiral_val": "RGB_MATRIX_BAND_SPIRAL_VAL",
    "cycle_all": "RGB_MATRIX_CYCLE_ALL",
    "cycle_left_right": "RGB_MATRIX_CYCLE_LEFT_RIGHT",
    "cycle_up_down": "RGB_MATRIX_CYCLE_UP_DOWN",
    "cycle_out_in": "RGB_MATRIX_CYCLE_OUT_IN",
    "cycle_out_in_dual": "RGB_MATRIX_CYCLE_OUT_IN_DUAL",
    "rainbow_moving_chevron": "RGB_MATRIX_RAINBOW_MOVING_CHEVRON",
    "cycle_pinwheel": "RGB_MATRIX_CYCLE_PINWHEEL",
    "cycle_spiral": "RGB_MATRIX_CYCLE_SPIRAL",
    "dual_beacon": "RGB_MATRIX_DUAL_BEACON",
    "rainbow_beacon": "RGB_MATRIX_RAINBOW_BEACON",
    "rainbow_pinwheels": "RGB_MATRIX_RAINBOW_PINWHEELS",
    "flower_blooming": "RGB_MATRIX_FLOWER_BLOOMING",
    "raindrops": "RGB_MATRIX_RAINDROPS",
    "jellybean_raindrops": "RGB_MATRIX_JELLYBEAN_RAINDROPS",
    "hue_breathing": "RGB_MATRIX_HUE_BREATHING",
    "hue_pendulum": "RGB_MATRIX_HUE_PENDULUM",
    "hue_wave": "RGB_MATRIX_HUE_WAVE",
    "pixel_fractal": "RGB_MATRIX_PIXEL_FRACTAL",
    "pixel_flow": "RGB_MATRIX_PIXEL_FLOW",
    "pixel_rain": "RGB_MATRIX_PIXEL_RAIN",
    "typing_heatmap": "RGB_MATRIX_TYPING_HEATMAP",
    "digital_rain": "RGB_MATRIX_DIGITAL_RAIN",
    "solid_reactive_simple": "RGB_MATRIX_SOLID_REACTIVE_SIMPLE",
    "solid_reactive": "RGB_MATRIX_SOLID_REACTIVE",
    "solid_reactive_wide": "RGB_MATRIX_SOLID_REACTIVE_WIDE",
    "solid_reactive_multiwide": "RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE",
    "solid_reactive_cross": "RGB_MATRIX_SOLID_REACTIVE_CROSS",
    "solid_reactive_multicross": "RGB_MATRIX_SOLID_REACTIVE_MULTICROSS",
    "solid_reactive_nexus": "RGB_MATRIX_SOLID_REACTIVE_NEXUS",
    "solid_reactive_multinexus": "RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS",
    "splash": "RGB_MATRIX_SPLASH",
    "multisplash": "RGB_MATRIX_MULTISPLASH",
    "solid_splash": "RGB_MATRIX_SOLID_SPLASH",
    "solid_multisplash": "RGB_MATRIX_SOLID_MULTISPLASH",
    "starlight": "RGB_MATRIX_STARLIGHT",
    "starlight_dual_hue": "RGB_MATRIX_STARLIGHT_DUAL_HUE",
    "starlight_dual_sat": "RGB_MATRIX_STARLIGHT_DUAL_SAT",
    "riverflow": "RGB_MATRIX_RIVERFLOW",
}

EFFECT_TYPES: tuple[EffectDef, ...] = (
    # ─── Effets ambiants (pas besoin d'appui touche) ───
    EffectDef("static",                    "Solid Color",                "Couleur unique uniforme sur tout le clavier.",                                        "solid",       "ambient"),
    EffectDef("alphas_mods",               "Alphas / Mods",              "Touches alpha d'une couleur, modificateurs d'une autre.",                            "two_zone",    "ambient"),
    EffectDef("gradient_up_down",          "Gradient Haut / Bas",        "Dégradé vertical continu de haut en bas.",                                           "gradient_v",  "ambient"),
    EffectDef("gradient_left_right",       "Gradient Gauche / Droite",   "Dégradé horizontal continu de gauche à droite.",                                     "gradient_h",  "ambient"),
    EffectDef("breathing",                 "Breathing",                  "Toutes les touches pulsent lentement entre couleur et noir.",                         "breathing",   "ambient"),
    EffectDef("band_sat",                  "Band Saturation",            "Bande de saturation défilant vers le bas.",                                           "band_v",      "ambient"),
    EffectDef("band_val",                  "Band Value",                 "Bande de luminosité défilant vers le bas.",                                           "band_v",      "ambient"),
    EffectDef("band_pinwheel_sat",         "Band Pinwheel Sat",          "Bande de saturation tournant en roue depuis le centre.",                              "pinwheel",    "ambient"),
    EffectDef("band_pinwheel_val",         "Band Pinwheel Val",          "Bande de luminosité tournant en roue depuis le centre.",                              "pinwheel",    "ambient"),
    EffectDef("band_spiral_sat",           "Band Spiral Sat",            "Spirale de saturation s'enroulant depuis le centre.",                                 "spiral",      "ambient"),
    EffectDef("band_spiral_val",           "Band Spiral Val",            "Spirale de luminosité s'enroulant depuis le centre.",                                 "spiral",      "ambient"),
    EffectDef("cycle_all",                 "Cycle All",                  "Toutes les touches changent de teinte simultanément — arc-en-ciel global.",           "cycle_all",   "ambient"),
    EffectDef("cycle_left_right",          "Cycle Gauche → Droite",      "Vague arc-en-ciel balayant de gauche à droite.",                                      "cycle_lr",    "ambient"),
    EffectDef("cycle_up_down",             "Cycle Haut → Bas",           "Vague arc-en-ciel balayant de haut en bas.",                                          "cycle_ud",    "ambient"),
    EffectDef("cycle_out_in",              "Cycle Extérieur → Centre",   "Vague arc-en-ciel entrant des bords vers le centre.",                                 "cycle_out_in","ambient"),
    EffectDef("cycle_out_in_dual",         "Cycle Ext→Centre (dual)",    "Double vague arc-en-ciel symétrique depuis chaque demi-clavier.",                     "cycle_out_in","ambient"),
    EffectDef("rainbow_moving_chevron",    "Rainbow Chevron",            "Chevron arc-en-ciel se déplaçant de gauche à droite.",                                "cycle_lr",    "ambient"),
    EffectDef("cycle_pinwheel",            "Cycle Pinwheel",             "Arc-en-ciel tournant en roue depuis le centre.",                                      "pinwheel",    "ambient"),
    EffectDef("cycle_spiral",              "Cycle Spiral",               "Arc-en-ciel en spirale s'éloignant du centre.",                                       "spiral",      "ambient"),
    EffectDef("dual_beacon",               "Dual Beacon",                "Deux phares tournants avec couleurs opposées.",                                        "pinwheel",    "ambient"),
    EffectDef("rainbow_beacon",            "Rainbow Beacon",             "Phare arc-en-ciel tournant lentement.",                                               "pinwheel",    "ambient"),
    EffectDef("rainbow_pinwheels",         "Rainbow Pinwheels",          "Plusieurs tourbillons arc-en-ciel simultanés.",                                        "pinwheel",    "ambient"),
    EffectDef("flower_blooming",           "Flower Blooming",            "Motif de fleur s'épanouissant progressivement.",                                      "breathing",   "ambient"),
    EffectDef("raindrops",                 "Raindrops",                  "Touches colorées aléatoirement comme des gouttes de pluie.",                           "raindrops",   "ambient"),
    EffectDef("jellybean_raindrops",       "Jellybean Raindrops",        "Pluie de couleurs bonbon pastel aléatoires.",                                          "raindrops",   "ambient"),
    EffectDef("hue_breathing",             "Hue Breathing",              "Toutes les touches pulsent en faisant évoluer la teinte.",                            "breathing",   "ambient"),
    EffectDef("hue_pendulum",              "Hue Pendulum",               "Teinte oscillant en pendule de gauche à droite.",                                      "cycle_lr",    "ambient"),
    EffectDef("hue_wave",                  "Hue Wave",                   "Vague de teinte traversant le clavier de gauche à droite.",                           "cycle_lr",    "ambient"),
    EffectDef("pixel_fractal",             "Pixel Fractal",              "Motif fractal coloré évoluant en continu.",                                            "raindrops",   "ambient"),
    EffectDef("pixel_flow",                "Pixel Flow",                 "Flux de pixels colorés défilant sur le clavier.",                                      "cycle_lr",    "ambient"),
    EffectDef("pixel_rain",                "Pixel Rain",                 "Pluie de pixels colorés tombant sur le clavier.",                                      "raindrops",   "ambient"),
    EffectDef("starlight",                 "Starlight",                  "Étoiles scintillant aléatoirement.",                                                  "raindrops",   "ambient"),
    EffectDef("starlight_dual_hue",        "Starlight (dual hue)",       "Étoiles scintillant en deux teintes alternées.",                                      "raindrops",   "ambient"),
    EffectDef("starlight_dual_sat",        "Starlight (dual sat)",       "Étoiles scintillant en deux saturations alternées.",                                  "raindrops",   "ambient"),
    EffectDef("riverflow",                 "Riverflow",                  "Animation fluide imitant le courant d'une rivière.",                                  "cycle_lr",    "ambient"),
    # ─── Effets réactifs (déclenchés par appui touche) ───
    EffectDef("typing_heatmap",            "Typing Heatmap",             "Carte de chaleur montrant les touches les plus pressées.",                             "heatmap",     "reactive"),
    EffectDef("digital_rain",              "Digital Rain",               "Pluie de chiffres style Matrix — vert tombant.",                                       "raindrops",   "reactive"),
    EffectDef("solid_reactive_simple",     "Solid Reactive Simple",      "La touche pressée s'illumine brièvement en couleur primaire.",                        "reactive",    "reactive"),
    EffectDef("solid_reactive",            "Solid Reactive",             "La touche pressée illumine ses voisines en fondu.",                                    "reactive",    "reactive"),
    EffectDef("solid_reactive_wide",       "Solid Reactive Wide",        "Grande zone lumineuse autour de la touche pressée.",                                   "reactive",    "reactive"),
    EffectDef("solid_reactive_multiwide",  "Solid Reactive Multiwide",   "Multiples grandes zones lumineuses simultanées.",                                      "reactive",    "reactive"),
    EffectDef("solid_reactive_cross",      "Solid Reactive Cross",       "Croix lumineuse s'allumant à la pression.",                                            "reactive",    "reactive"),
    EffectDef("solid_reactive_multicross", "Solid Reactive Multicross",  "Multiples croix lumineuses simultanées.",                                              "reactive",    "reactive"),
    EffectDef("solid_reactive_nexus",      "Solid Reactive Nexus",       "Anneau lumineux se propageant depuis la touche pressée.",                              "reactive",    "reactive"),
    EffectDef("solid_reactive_multinexus", "Solid Reactive Multinexus",  "Multiples anneaux lumineux simultanés.",                                               "reactive",    "reactive"),
    EffectDef("splash",                    "Splash",                     "Éclaboussure arc-en-ciel depuis la touche pressée.",                                   "reactive",    "reactive"),
    EffectDef("multisplash",               "Multisplash",                "Multiples éclaboussures arc-en-ciel simultanées.",                                     "reactive",    "reactive"),
    EffectDef("solid_splash",              "Solid Splash",               "Éclaboussure couleur solide depuis la touche pressée.",                                "reactive",    "reactive"),
    EffectDef("solid_multisplash",         "Solid Multisplash",          "Multiples éclaboussures couleur solide simultanées.",                                  "reactive",    "reactive"),
)

# IDs de tous les effets QMK natifs (pour le sélecteur enabled/disabled)
ALL_BUILTIN_IDS: list[str] = [e.id for e in EFFECT_TYPES if not e.custom and e.id != "static"]

# Ordre exact de l'enum QMK — doit correspondre à rgb_matrix_effects.inc dans vial-qmk.
# Les effets custom (timeline) sont ajoutés APRÈS cette liste par le template_generator.
QMK_ENUM_ORDER: list[str] = [
    "static",
    "alphas_mods",
    "gradient_up_down",
    "gradient_left_right",
    "breathing",
    "band_sat",
    "band_val",
    "band_pinwheel_sat",
    "band_pinwheel_val",
    "band_spiral_sat",
    "band_spiral_val",
    "cycle_all",
    "cycle_left_right",
    "cycle_up_down",
    "rainbow_moving_chevron",   # avant cycle_out_in dans QMK !
    "cycle_out_in",
    "cycle_out_in_dual",
    "cycle_pinwheel",
    "cycle_spiral",
    "dual_beacon",
    "rainbow_beacon",
    "rainbow_pinwheels",
    "flower_blooming",
    "raindrops",
    "jellybean_raindrops",
    "hue_breathing",
    "hue_pendulum",
    "hue_wave",
    "pixel_rain",               # avant pixel_flow / pixel_fractal dans QMK !
    "pixel_flow",
    "pixel_fractal",
    "typing_heatmap",
    "digital_rain",
    "solid_reactive_simple",
    "solid_reactive",
    "solid_reactive_wide",
    "solid_reactive_multiwide",
    "solid_reactive_cross",
    "solid_reactive_multicross",
    "solid_reactive_nexus",
    "solid_reactive_multinexus",
    "splash",
    "multisplash",
    "solid_splash",
    "solid_multisplash",
    # starlight_smooth omis (pas dans notre liste d'effets)
    "starlight",
    "starlight_dual_sat",       # SAT avant HUE dans QMK !
    "starlight_dual_hue",
    "riverflow",
]

# Noms OLED abrégés — exactement 10 caractères (2 lignes × 5 chars sur 128×32)
EFFECT_OLED_NAME: dict[str, str] = {
    "static":                    "SolidColor",
    "alphas_mods":               "AlphaMods ",
    "gradient_up_down":          "Grad UpDwn",
    "gradient_left_right":       "Grad LfRgt",
    "breathing":                 "Breathing ",
    "band_sat":                  "Band Sat  ",
    "band_val":                  "Band Val  ",
    "band_pinwheel_sat":         "BdPinSat  ",
    "band_pinwheel_val":         "BdPinVal  ",
    "band_spiral_sat":           "BdSpiSat  ",
    "band_spiral_val":           "BdSpiVal  ",
    "cycle_all":                 "CycleAll  ",
    "cycle_left_right":          "CycleLfRgt",
    "cycle_up_down":             "CycleUpDwn",
    "rainbow_moving_chevron":    "RnbMvChvrn",
    "cycle_out_in":              "CycleOutIn",
    "cycle_out_in_dual":         "CycleOIDul",
    "cycle_pinwheel":            "CyclePinwl",
    "cycle_spiral":              "CycleSpirl",
    "dual_beacon":               "Dual Beacn",
    "rainbow_beacon":            "RainbBeacn",
    "rainbow_pinwheels":         "RainbPinwl",
    "flower_blooming":           "FlowrBloom",
    "raindrops":                 "Rain drops",
    "jellybean_raindrops":       "JellyDrops",
    "hue_breathing":             "Hue  Breth",
    "hue_pendulum":              "Hue  Pendl",
    "hue_wave":                  "Hue  Wave ",
    "pixel_rain":                "PixelRain ",
    "pixel_flow":                "PixelFlow ",
    "pixel_fractal":             "PixelFrctl",
    "typing_heatmap":            "TypngHtmap",
    "digital_rain":              "DigtlRain ",
    "solid_reactive_simple":     "SldReSimpl",
    "solid_reactive":            "SolidReact",
    "solid_reactive_wide":       "SldReWide ",
    "solid_reactive_multiwide":  "SldReMulWd",
    "solid_reactive_cross":      "SldReCross",
    "solid_reactive_multicross": "SldReMulCr",
    "solid_reactive_nexus":      "SldReNexus",
    "solid_reactive_multinexus": "SldReMulNx",
    "splash":                    "SplasH    ",
    "multisplash":               "MultiSplsh",
    "solid_splash":              "SolidSplsh",
    "solid_multisplash":         "SldMuSplsh",
    "starlight":                 "Star light",
    "starlight_dual_sat":        "StarDulSat",
    "starlight_dual_hue":        "StarDulHue",
    "riverflow":                 "Riverflow ",
}

# Effets nécessitant RGB_MATRIX_FRAMEBUFFER_EFFECTS pour compiler
NEEDS_FRAMEBUFFER: frozenset[str] = frozenset({"typing_heatmap", "digital_rain"})
